### ISSUE TITLE
Exception when decompiling lunar

### ISSUE THREAD

**Issue by MrAn0nym** [Decencies/LunarRemapper#2]
```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:277)
	at club.decencies.remapper.lunar.Main.lambda$main$12(Main.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at club.decencies.remapper.lunar.Main.main(Main.java:66)
```

Happend with 1.17, 1.16 and java versions 8, 17 & 18

Jar build via jitpack from 777d8a21ba9e83776f03aa27b94cb177f9bcfd8f (https://jitpack.io/com/github/Decencies/LunarRemapper/777d8a21ba/LunarRemapper-777d8a21ba.jar)

*Edit: Running on linux btw

**Comment by mrcorpz** [comment]
I got this with your jar 

$ java -jar LunarRemapper-777d8a21ba.jar
@@@@@@@@@@@@@@@@@==@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@==-------=@@@@@@@@@@@@@
@@@@@@@@@@=-----@@@@@@=---=@@@@@@@@@
@@@@@@@@= -=@-  @=@@@@@@@@- @@@@@@@@         Lunar Remapper
@@@@@@@@- @@    =@@@@@@@=@= =@@@@@@@         Version: 1.0-SNAPSHOT
@@@@@@@@- @@     -=@=@@@=@= =@@@@@@@         Developed by Decencies
@@@@@@@@- @=@-         -@@= =@@@@@@@
@@@@@@@@- -               - -@@@@@@@
@@@@@@@@@@===---     -=-===@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at club.decencies.remapper.lunar.util.FileUtil.walk(FileUtil.java:18)
        at club.decencies.remapper.lunar.Main.main(Main.java:49)

**Comment by Decencies** [comment]
> ```
> Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
> 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:277)
> 	at club.decencies.remapper.lunar.Main.lambda$main$12(Main.java:75)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at club.decencies.remapper.lunar.Main.main(Main.java:66)
> ```
> 
> Happend with 1.17, 1.16 and java versions 8, 17 & 18
> 
> Jar build via jitpack from [777d8a2](https://github.com/Decencies/LunarRemapper/commit/777d8a21ba9e83776f03aa27b94cb177f9bcfd8f) (https://jitpack.io/com/github/Decencies/LunarRemapper/777d8a21ba/LunarRemapper-777d8a21ba.jar)
> 
> *Edit: Running on linux btw

Looks like Lunar have updated the version of Java used to compile once again, updating asm to `9.2` should resolve the issue.

**Comment by Decencies** [comment]
> I got this with your jar
> 
> $ java -jar LunarRemapper-777d8a21ba.jar @@@@@@@@@@@@@@@@@==@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@==-------=@@@@@@@@@@@@@ @@@@@@@@@@=-----@@@@@@=---=@@@@@@@@@ @@@@@@@@= -=@- @=@@@@@@@@- @@@@@@@@ Lunar Remapper @@@@@@@@- @@ =@@@@@@@=@= =@@@@@@@ Version: 1.0-SNAPSHOT @@@@@@@@- @@ -=@=@@@=@= =@@@@@@@ Developed by Decencies @@@@@@@@- @=@- -@@= =@@@@@@@ @@@@@@@@- - - -@@@@@@@ @@@@@@@@@@===--- -=-===@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Exception in thread "main" java.lang.NullPointerException at java.util.Objects.requireNonNull(Objects.java:203) at club.decencies.remapper.lunar.util.FileUtil.walk(FileUtil.java:18) at club.decencies.remapper.lunar.Main.main(Main.java:49)

Looks like you haven't set up the workspace properly, please read the README. 

If this issue persists please notify me with your Java version used to compile & run the program.

Regards,
Decencies.
