### ISSUE TITLE
Someone can drop me LC Legacy?

### ISSUE THREAD

**Issue by Dani-error** [Decencies/LunarRemapper#4]
When I run the remapper, nothing happens so I opened the Main.java class and I saw that I need a Legacy Lunar version... So, anyone can drop me a Lunar Client Legacy Version?

**Comment by rastiqdev** [comment]
Sorry I don't have any Lunar Client Legacy jar

**Comment by MrAn0nym** [comment]
> I saw that I need a Legacy Lunar version

Where?

**Comment by Dani-error** [comment]
// match <major>.<minor>.<patch>.json (legacy lunar versions) Line 130

**Comment by Dani-error** [comment]
Or anyone can send his project structure?

**Comment by Decencies** [comment]
Temp fix for this, is to add a file name with the version within the lunar-prod.jar.

For example:

lunar-prod.jar for 1.8.9 would need a file with the name `1.8.9` within the root of the JAR. (File ext. does not matter)
