### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Mqrry** [Decencies/LunarRemapper#7]
@@@@@@@@@@@@@@@@@==@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@==-------=@@@@@@@@@@@@@
@@@@@@@@@@=-----@@@@@@=---=@@@@@@@@@
@@@@@@@@= -=@-  @=@@@@@@@@- @@@@@@@@         Lunar Remapper
@@@@@@@@- @@    =@@@@@@@=@= =@@@@@@@         Version: 1.0-SNAPSHOT
@@@@@@@@- @@     -=@=@@@=@= =@@@@@@@         Developed by Decencies
@@@@@@@@- @=@-         -@@= =@@@@@@@
@@@@@@@@- -               - -@@@@@@@
@@@@@@@@@@===---     -=-===@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[16:54:07] [main/INFO]: Loaded OptiFine version OptiFine_1.8.9_HD_U_M6_pre2.

Process finished with exit code 0
JDK: 1.8.0_321 Oracle OpenJDK
Path: https://imgur.com/a/j02plGS

**Comment by Decencies** [comment]
Fix on the way, read the temporary fix for this issue in the updated README.
